### ISSUE TITLE
cute_dsp causes cute_sound to crash in cs_mix

### ISSUE THREAD

**Issue by mijagourlay** [themattrosen/cute_dsp#1]
Running on Window 10 using cute_sound 1.11. Compiling with Visual Studio.

Running (cute_dsp) echo_test causes (cute_sound) cs_mix to crash due to...

    Unhandled exception: 0xC0000005: Access violation reading location 0xffffffff.

...at this line in cs_mix (in cute_sound):

    // apply volume, load samples into float buffers
    switch (loaded->channel_count)
    {
    case 1:
        for (int i = delay_wide; i < mix_wide - delay_wide; ++i) {
            cs__m128 A = cA[i + offset_wide]; // THIS LINE CRASHES

I also tried adding cute_dsp to both the cute_sound test files, and my project. All produce the same outcome -- that crash in cs_mix.

BTW notice this line vanilla echo_test:

	int buffered_seconds = 5; // number of seconds the buffer will hold in memory. want this long enough in case of frame-delays

In echo_test, that parameter is passed into cs_make_context:

	cs_context_t* sound_ctx = cs_make_context(GetActiveWindow(), frequency, /*latency_in_Hz,*/ buffered_seconds, num_elements_in_playing_pool, 0);

The parameter passed in as "buffered_seconds" is actually buffered_samples. The units are samples, not seconds. So "5" is probably not a reasonable value. So I increased that to various values, including 8192 and up. To test my understanding of this parameter, I passed in "5" in the cute_sound test code and the outcome was that no sound played.

**Comment by themattrosen** [comment]
Hi, sorry it took so long to get to this. It looks like cute_sound has had several updates. I've updated the tests to have better values there, and cleaned up some of the unused variables. I haven't been able to repro the crash. Let me know if this issue persists!
